#service: black_suite
#image: anechka5/black_suite

#registry:
#   server: docker.io
#   username: anechka5
#   password:
#     - KAMAL_REGISTRY_PASSWORD

#builder:
#  arch:
#    - amd64

#servers:
#  web:
#    hosts:
#      - acelan.ru

#accessories:
#  db:
#    image: postgres:15
#    host: acelan.ru
#    port: 5433
#    env:
#      clear:
#        POSTGRES_DB: black_suite_production
#        POSTGRES_USER: black_suite
#        POSTGRES_PASSWORD: POSTGRES_PASSWORD
#    directories:
#      - postgres_data:/var/lib/postgresql/data
#    options:
#      cpus: 0.5
#      memory: 512M

#env:
#  clear:
#    RAILS_ENV: production
#  secret:
#    - RAILS_MASTER_KEY

service: black_suite
image: anechka5/black_suite

registry:
  server: docker.io
  username: anechka5
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - amd64
  context: "."
  dockerfile: Dockerfile

servers:
  web:
    hosts:
      - acelan.ru
    env:
      RAILS_SERVE_STATIC_FILES: true
    proxy:
      ssl: true
      app_port: 3000
      host: acelan.ru

accessories:
  db:
    image: postgres:16
    host: acelan.ru
    port: 5433
    env:
      clear:
        POSTGRES_DB: black_suite_production
        POSTGRES_USER: black_suite
      secret:
        - POSTGRES_PASSWORD
    directories:
      - postgres_data:/var/lib/postgresql/data
    options:
      cpus: 0.5
      memory: 512M

env:
  clear:
    RAILS_ENV: production
    POSTGRES_DB: black_suite_production
    POSTGRES_USER: black_suite
    POSTGRES_HOST: black_suite-db
    POSTGRES_PORT: "5432"
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
