service: black_suite
image: anechka5/black_suite

registry:
  server: docker.io
  username: anechka5
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - amd64
  context: "."
  dockerfile: Dockerfile

servers:
  web:
    hosts:
      - 2.56.178.138
    env:
      RAILS_SERVE_STATIC_FILES: true
    proxy:
      ssl: false
      app_port: 3000
      host: 2.56.178.138
    options:
      network: "private"

  sidekiq:
    hosts:
      - 2.56.178.138
    cmd: bundle exec sidekiq
    env:
      RAILS_SERVE_STATIC_FILES: true
    options:
      network: "private"

accessories:
  db:
    image: postgres:16
    host: 2.56.178.138
    port: 5433
    env:
      clear:
        POSTGRES_DB: black_suite_production
        POSTGRES_USER: black_suite
      secret:
        - POSTGRES_PASSWORD
    directories:
      - postgres_data:/var/lib/postgresql/data
    options:
      cpus: 0.5
      memory: 512M

  redis:
    image: redis:latest
    host: 2.56.178.138
    port: 6379
    cmd: "redis-server --requirepass <%= ENV['REDIS_PASSWORD'] %>"
    directories:
      - redis_data:/data
    options:
      network: "private"

env:
  clear:
    RAILS_ENV: production
    POSTGRES_DB: black_suite_production
    POSTGRES_USER: black_suite
    POSTGRES_HOST: black_suite-db
    POSTGRES_PORT: "5432"
    ACTION_CABLE_ALLOWED_ORIGINS: "http://2.56.178.138:3000"
    ACTION_CABLE_DISABLE_REQUEST_FORGERY_PROTECTION: "true"
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - REDIS_URL
    - REDIS_PASSWORD
    - KAMAL_REGISTRY_PASSWORD
